dist: focal
language: C

branches:
  only:
  - master

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo apt-get install -y libnuma-dev
  - sudo apt-get install -y linux-modules-5.4.0-1018-gcp linux-headers-$(uname -r)
  - sudo apt install python3-pip -y
  - sudo pip3 install setuptools
  - sudo pip3 install meson
  - sudo pip3 install ninja
  - sudo pip3 install pyelftools

script: ./boot.sh || travis_terminate 1;
